- alias: 'Normal Weekday Lighting'
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
      - condition: time
        before: '21:00:00'
      - condition: or
        conditions:
        - condition: state
          entity_id: 'device_tracker.arretx_jons_phone'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.bizzerk2_melanies_phone'
          state: 'home'
  action:
    - delay:
        milliseconds: 2690
    - service: switch.turn_on
      entity_id: switch.entertainment_center
    - service: switch.turn_on
      entity_id: switch.patio_lights
