- alias: 'Turn Off Entertainment Center Lights'
  trigger:
    - platform: state
      entity_id: device_tracker.bizzerk2_melanies_phone
      from: 'home'
    - platform: state
      entity_id: device_tracker.arretx_jons_phone
      from: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.bizzerk2_melanies_phone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.arretx_jons_phone
        state: 'not_home'
      - condition: state
        entity_id: switch.entertainment_center
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.entertainment_center
