#### TIME/DATE ##################################
#- platform: time_date
#  display_options:
#      - 'time'
#      - 'date'

- platform: worldclock
  time_zone: America/Phoenix
  name: 'Phoenix'

#Displays an UP TIME sensor.
- platform: uptime
  name: Up Time
  unit_of_measurement: hours
